apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nanzi-ai-agent

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: nanzi-ai-agent
    newName: nanzi-ai-agent
    newTag: latest
